title: Manc-COJO
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://light156.github.io/multi-ancestry-COJO

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/light156/multi-ancestry-COJO
